#!/usr/bin/env node
const smtp = [



    
    {
        host: '',
        port: 587,
        secure: false,
        username: '',
        password: '',
        from_email: '',
      },
      
       {
        host: '',
        port: 587,
        secure: false,
        username: '',
        password: '',
        from_email: '',
      },
    
]



let setup = {
    key: "",
    MultipleSmtp: "ROTATE", // "ROTATE" AND "QUEUE" 

    mail_priority: "high", // high , medium, low
    sleep_time: 1000,// 1000 for 1 second (can setup 0)
    isMultiThread: true,
    howManyThread: 3, // set as you want , no limit


    from_name: "",
    mail_subject: "Test Smtp",


    test_frommail: false,
    frommail_filename: "frommail.txt",

    replyTo: "",
    email_test: false, // true, false
    test_every: 1,
    email_destination: "NOIR@NOIR.COM",

    letter: "letter.html",
    encode_letter: "base64", // there are 2 options "hex" and "base64"

    useAttachment: false,
    encode_attachment: "base64", // there are 2 options "hex" and "base64"

    mailist: "mailist.txt", // file name mailist

    pdfOrientation: "potrait", // "potriat" or "landscape"for pdf attachment

    LetterToImage: false,
    fileName_LetterToImage: "./letterToImage.html",

    useGrabLogo: false, // true false
    defaultLogo: "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b?ver=5c31",
    useMylogo: false,

    widthImage_for_grabLogo_letter: "",
    heightImage_for_grabLogo_letter: "",

    widthImage_for_myLogo_letter: "",
    heightImage_for_myLogo_letter: "",


    widthImage_for_grabLogo_attachment: "",
    heighttImage_for_grabLogo_attachment: "",

    widthImage_for_myLogo_attachment: "",
    heighttImage_for_myLogo_attachment: "",

    URLencode: "https://google.com",
}


const myLOGO = [
    {
        function_name: "MYLOGO1",
        nameFile: "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b?ver=5c31"
    }
]

const proxy = {

    test_proxy: false,
    proxy_type: "socks5", // socks4, socks5, http
    proxy_username: "",
    proxy_password: "",
    proxy_list : "NOIR4/proxy.txt", // file name proxy list
    proxy_live: "proxy_live.txt", // file name proxy live
    final_proxy: "",
}


const attachment_EML = {
    use_EML: false,

    attachment_name_EML: "<COMPANYNAME>.eml",
    letter_eml: "attachment_EML.html",




    subject_eml: "<COMPANYNAME> Report Payment",
    from_email_eml: "admin@<DOMAIN>",

    useAttachment_EML: true,
    attachment: [
        {
            attachmentName: "<RANDNUM5>#<COMPANYNAME>.html",
            path: "EML/attachment.html"
        },

    ],


}


// send multiple attachment as youu want

const attachment = [
    {   // file on disk as an attachment
        filename: '.htm',
        path: 'attachment.html', // stream this file
        attachmentToPdf: false,
        encryptAttachment: true,

    },

]

const setup_time_date = {
    time_zone: "America/Adak", //https://en.wikipedia.org/wiki/List_of_tz_database_time_zones -> list all of time zone in the world
    timezone_name: "long", // "long" and "short"
    time_format_lang: "en",
}

//generate your number random 
const generate_random_number = [
    {
        name: "RANDNUM1",
        lengt_value: 1
    },
    {
        name: "RANDNUM2",
        lengt_value: 2
    },
    {
        name: "RANDNUM3",
        lengt_value: 3
    },
    {
        name: "RANDNUM4",
        lengt_value: 4
    },
    {
        name: "RANDNUM5",
        lengt_value: 5
    },
]

const generate_random_string = [
    {
        name: "random_string_3",
        lengt_value: 3,
        type: "UPPERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
    },
    {
        name: "random_string_4",
        lengt_value: 4,
        type: "LOWERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
    },
    {
        name: "random_string_1",
        lengt_value: 1,
        type: "LOWERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
    },
    {
        name: "random_string_2",
        lengt_value: 2,
        type: "LOWERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
    },
    {
        name: "random_string_5",
        lengt_value: 5,
        type: "LOWERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
    },
]

const menu = {
    change_ip: false,
    requireTLS: true,
    ignoreTLS: false,
    rejectUnauthorized: false,
    maxMessages: 1,
    maxConnections: 1,

}

module.exports = { smtp, setup, generate_random_number, generate_random_string, setup_time_date, attachment, myLOGO, attachment_EML, menu, proxy };
